sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - $HOME/.coursier

language: scala

scala:
  - 2.12.10
  - 2.13.1

jdk:
  - openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION test mimaReportBinaryIssues

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -exec rm {} +
  - find $HOME/.ivy2 -name "ivydata-*.properties" -exec rm {} +
